root -l -b -q 'PlotterBsKsKs.C("InvMass")'
root -l -b -q 'PlotterBsKsKs.C("pip_PT")'
root -l -b -q 'PlotterBsKsKs.C("pim_PT")'
root -l -b -q 'PlotterBsKsKs.C("Km_PT")'
root -l -b -q 'PlotterBsKsKs.C("Kp_PT")'
