root -l -b -q 'RunAnalysisBsKsKs.C("DecayTree", "DecayTree")'
#root -l -b -q 'RunAnalysisBsKsKs.C("DTT_2016_Reco16Strip28_Down_BHADRON", "Bs2KpiKpi/DecayTree")'
#root -l -b -q 'RunAnalysisBsKsKs.C("DTT_2016_Reco16Strip28_Up_BHADRON", "Bs2KpiKpi/DecayTree")'
#root -l -b -q 'RunAnalysisBsKsKs.C("DTT_2016_Reco16Strip28_Down_BHADRON.root", "Bs2KpiKpi/DecayTree")'
#root -l -b -q 'RunAnalysisBsKsKs.C("DTT_2016_Reco16Strip28_Up_BHADRON.root", "Bs2KpiKpi/DecayTree")'
